### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by danielgruber8** [markuta/authy-backup#1]
Hi,

Is there a way to get a json file instead of QR codes for bulk import into Aegis / 2FAS / Ente?

**Comment by markuta** [comment]
I was initially thinking about this, but the problem is there are different export/import formats. I believe Aegis supports importing the raw `com.authy.storage.tokens.authenticator.xml` file, among other ways.

Anyway, I've added really basic JSON export feature, using the Aegis format. It writes a file to the current directory. P.S. not much testing has been done.
